NUnit_Engine: running methods extended and bugfixed
BHoM/Test_Toolkit pull request #439
Opened 2023-05-17 22:47 UTC by pawelbaran

### Issues addressed by this PR

 Closes #435
 Closes #436

 

 ### Test files

To be added.

 ### Changelog

 ### Additional comments

Not ideal to mix bug + feature, but this is a result of a wider exploration. Happy to split into separate PRs before merging along with targeted test scripts being added.

2023-05-18 17:15 UTC, FraserGreenroyd requested changes
Have made comments on the code for some capitalisation things on the methods I like.

I don't see the need for a `TestRun RunTests(IEnumerable<string> filePaths)` method, at least not without the original `TestRun RunTests(string filePath)` method that we had before, as that places unnecessary onerous on the calling assembly to convert a single string file path into a list just to use the method for one file path. In particular, this is what BHoMBot is using - as it executes each individual test file in sequence and never all at once.

So if we truly see a need somewhere for the `IEnumerable` option, then fine, but we also need the singular file path option to be kept as well.  Personally, I would rather do away with the IEnumerable` option and just have the singular - as it's less onerous for the calling assembly to break out their list than to force one to provide a list when they only have one (as is the case of the bot), but if there's a valid argument for an `IEnumerable` option then we can keep it providing we put the singular back in as well.

I also don't like the changing of the XML Properties around `Settings` and `Properties` - it would be good to understand better what the crash specifically was to understand how those changes fix it. I think this will break the existing set up for the bot. I'm not against updating the bot to match this framework if we have to, but I think there's a different issue possibly in play, but without any screenshots/further information on the PR/issue #435 it's hard to say. So this needs further discussion I think.

I have no qualms with the breaking out of the conversion from the XML Test Result to TestRun becoming its own method in the Convert class, that makes logical sense given the advancements we're aiming for with this PR so 👍 on that from me.

In summary, I think this is a decent start for upgrading the NUnit_Engine as we continue to grow out our testing capabilities, but a couple of things would be good to chat through next week when you're back @pawelbaran to make sure we're leveraging the right things for the right approaches (bot/BIM/other) 😄

2023-05-18 17:15 UTC, FraserGreenroyd commented on NUnit_Engine/Query/NunitTestClasses.cs
> +        public static List<Type> NunitTestClasses(this Assembly assembly)
```suggestion
        public static List<Type> NUnitTestClasses(this Assembly assembly)
```

2023-05-18 17:15 UTC, FraserGreenroyd commented on NUnit_Engine/Query/NunitTestMethods.cs
> +        public static List<MethodInfo> NunitTestMethods(this Assembly assembly)
```suggestion
        public static List<MethodInfo> NUnitTestMethods(this Assembly assembly)
```

2023-05-18 17:15 UTC, FraserGreenroyd commented on NUnit_Engine/Query/NunitTestMethods.cs
> +            return assembly.GetTypes().SelectMany(x => x.NunitTestMethods()).ToList();
```suggestion
            return assembly.GetTypes().SelectMany(x => x.NUnitTestMethods()).ToList();
```

2023-05-18 17:15 UTC, FraserGreenroyd commented on NUnit_Engine/Query/NunitTestMethods.cs
> +        public static List<MethodInfo> NunitTestMethods(this Type nunitClass)
```suggestion
        public static List<MethodInfo> NUnitTestMethods(this Type nunitClass)
```

2023-05-22 10:11 UTC, pawelbaran commented
Thanks @FraserGreenroyd for having a look.

Regarding the addition of `RunTests` that takes a collection of strings, please note I kept the overload with a single assembly path input, but added the ability to specify classes to test. Hopefully this will not break the bot, and if it does, then happy to bring the original setup back.
![image](https://github.com/BHoM/Test_Toolkit/assets/26874773/9a032930-baa9-407b-901b-3465e2590d70)

When it comes to serialisation, the code on `develop` struggles on deserialisation of collections in my cases, so I simply made it work. I have absolutely zero opinion on the design of the code here, my only need is to pass the information from XML to test result, so happy for you to take over the steering wheel. But probs best through it together - will schedule a call in the coming days 👍

2023-05-24 17:04 UTC, FraserGreenroyd commented
> I also don't like the changing of the XML Properties around `Settings` and `Properties`

I have reviewed this with @pawelbaran today and gone through some more tests, I now understand better why this change came in, and am happy with the change being made/kept as it does better support our workflows. Thanks @pawelbaran for being patient and working with me on this 😄

2023-05-24 22:19 UTC, pawelbaran commented
I think we are ready for re-review @FraserGreenroyd 👍

2023-05-24 22:19 UTC, pawelbaran commented
@BHoMBot check required

2023-05-25 08:15 UTC, pawelbaran commented
@FraserGreenroyd, there are some compliance checks failing, but none of the failures got introduced by this PR I think - are you fine with dispensating?

2023-05-25 09:02 UTC, FraserGreenroyd commented
> @FraserGreenroyd, there are some compliance checks failing, but none of the failures got introduced by this PR I think - are you fine with dispensating?

Ordinarily I would agree, however, the project-compliance failures are new following our change from `C:/ProgramData` to `$(ProgramData)` and are only being picked up on a PR by PR basis - you can use the bot to fix the project file and that should resolve those suitably.

For the documentation compliance - it is that you have an input attribute that doesn't match any input parameters (`filePath` instead of the param `filePaths`) so I would suggest we resolve that one.

2023-05-25 09:30 UTC, pawelbaran commented
> For the documentation compliance - it is that you have an input attribute that doesn't match any input parameters (`filePath` instead of the param `filePaths`) so I would suggest we resolve that one.

Yeah ofc. Not sure how did I read the test results 🤦 Thanks @FraserGreenroyd

2023-05-25 10:02 UTC, pawelbaran commented
@BHoMBot fix project file ref. 13751724291

2023-05-25 10:03 UTC, pawelbaran commented
@BHoMBot check compliance

2023-05-25 10:04 UTC, pawelbaran commented
@BHoMBot check required

2023-05-25 10:36 UTC, FraserGreenroyd approved these changes
Everything is in line with our discussion yesterday @pawelbaran thanks for the updates - happy to merge and deploy.

2023-05-25 10:36 UTC, merged